<?php
/**
 * Block report index template
 *
 * @category    Teeshter
 * @package     Teeshter_Wholesale
 * @author      teeshter
 */

/** @var \Teeshter\Wholesale\Block\Report\Index $block */
?>
<div class="teeshter-wholesale-report-index">
    <form
        id="form-product-report"
        action="<?php echo $block->getUrl('teeshter_wholesale/report/result') ?>"
        method="post">
        <?php echo $block->getBlockHtml('formkey') ?>
        <fieldset class="fieldset">
            <div class="field product">
                <label class="label" for="product"><span><?php echo __('Product Name') ?></span></label>
                <div class="control">
                    <select name="sku" data-validate="{required:true}">
                        <?php foreach ($block->getProductsOptionArray() as $product): ?>
                            <option
                                value="<?php echo $product['value'] ?>">
                                <?php echo $this->escapeHtml($product['label']) ?>
                            </option>
                        <?php endforeach; ?>
                    </select>
                </div>
            </div>
        </fieldset>
        <div class="actions-toolbar">
            <div class="primary">
                <button type="submit" class="action save primary">
                    <span><?php echo __('Submit') ?></span>
                </button>
            </div>
        </div>
    </form>
</div>
<script>
    require([
        'jquery',
        'mage/mage'
    ], function ($) {
        var dataForm = $('#form-product-report');
        dataForm.mage('validation', {});
    });
</script>
